# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # This has to be incremented when a new asset is incompatible with the previous version
    asset_version_major: 'assets/2'
    asset_version_minor: 5
    domain: 'https://wikireveal.com'
    assets_directory: '%kernel.project_dir%/public/assets'
    docs_directory: '%kernel.project_dir%/docs'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $languageProvider: !tagged_locator { tag: 'language', index_by: 'key', default_index_method: 'lang' }

    _instanceof:
        App\Language\LanguageInterface:
            tags: [ 'language' ]

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    App\Controller\IndexController:
        arguments:
            $docsDirectory: '%docs_directory%'

    App\Command\BuildCommand:
        arguments:
            $assetsDirectorySource: '%assets_directory%'
            $docsDirectoryDestination: '%docs_directory%'
            $assetVersion: '%asset_version_major%'
